- ethtxmanager/ethtxmanager.go
> fix logger

- etherman/etherman.go
> fix estimate gas

- .gitignore
- README.md
- ethtxmanager/config.go
- ethtxmanager/ethtxmanager.go
- ethtxmanager/interfaces.go
- ethtxmanager/memstorage.go
- ethtxmanager/monitoredtx.go
- ethtxmanager/monitoredtx_test.go
- test/main.go
refactor states and new fields in result
- @dpunish3r 
- @agnusmor
> refactor states and new fields

- ethtxmanager/ethtxmanager.go
changes log level
- @dpunish3r 
- @agnusmor
> change log level

- ethtxmanager/config.go
- ethtxmanager/ethtxmanager.go
- test/main.go
adds logs config to config struct
- @agnusmor 
- @dpunish3r
> add logs config to config struct

- ethtxmanager/config.go
- ethtxmanager/ethtxmanager.go
- ethtxmanager/memstorage.go
- ethtxmanager/monitoredtx.go
- test/main.go
- Adds consolidated state
- Removes need form "from" in config
- Add mutex to persistence file
- @dpunish3r 
- @agnusmor
> consolidated state

- ethtxmanager/config.go
- test/main.go
> fix config

- ethtxmanager/ethtxmanager.go
Implements nonce handling improvements proposed by @begmaroman on the zkevm-node's eth-tx-manager in this PR:
https://github.com/0xPolygonHermez/zkevm-node/pull/3338
- @dpunish3r 
- @agnusmor 
- @tclemos 
- @begmaroman
> Fix nonce too low

- .golangci.yml
- ethtxmanager/ethtxmanager.go
- ethtxmanager/memstorage.go
- ethtxmanager/rpcclient.go
Fixes linter
- @agnusmor 
- @dpunish3r
> Fix Linter

- ethtxmanager/config.go
- ethtxmanager/ethtxmanager.go
- ethtxmanager/interfaces.go
- ethtxmanager/memstorage.go
- test/main.go
- allow disable read L1 pool (default)
- allow emptying storage (RemoveAll)
- @dpunish3r 
- @agnusmor
> allow disable read L1 pool

- README.md
- ethtxmanager/ethtxmanager.go
- ethtxmanager/monitoredtx.go
- test/main.go
adds gas offset
- @dpunish3r 
- @agnusmor
> add gas offset

- ethtxmanager/ethtxmanager.go
- Print error data for calls to estimate gas
@agnusmor 
@ToniRamirezM
> print error data for calls to estimate gas

- go.mod
- go.sum
> update sync lib

- ethtxmanager/ethtxmanager.go
- ethtxmanager/monitoredtx.go
avoid estimating gas price to enable sending txs that depend on previous txs
> option to avoid gas estimationi

- ethtxmanager/ethtxmanager.go
- ethtxmanager/memstorage.go
- ethtxmanager/rpcclient.go
ensure tx order by creation date where retrieving them by status
> ensure tx order

- etherman/config.go
- etherman/etherman.go
- etherman/etherscan/etherscan.go
- etherman/etherscan/etherscan_test.go
- etherman/ethgasstation/ethgasstation.go
- etherman/ethgasstation/ethgasstation_test.go
- etherman/wait.go
- ethtxmanager/config.go
- ethtxmanager/ethtxmanager.go
- ethtxmanager/memstorage.go
- go.mod
- go.sum
- test/main.go
> change namespace

- ethtxmanager/ethtxmanager.go
compare local vs pending nonce
> compare local vs pending nonce

- ethtxmanager/ethtxmanager.go
Increase nonce of all pending txs while a nonce is reviewed after a failing tx.
> Increase noce of all pending txs

- ethtxmanager/ethtxmanager.go
- go.mod
- go.sum
- If a Tx fails to be sent to L1 shows a warning with a curl command to send manually
- bump go_singer to 0.0.6 to fix an error reading config for KMS
> feat: add a warn with a curl command if fails a Tx

- etherman/etherman.go
- etherman/etherman_test.go
Refactor gas price logic to return error on provider failure and allow zero gas price
> fix: handle zero gas price
